---
title: "Tidy_data"
author: "Kennedy Wade"
date: "2025-09-23"
output: html_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

this document willl show how to tidy data

##pivot longer

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()

pulse_df
```


```{r}
pulse_tidy_df = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi")

pulse_tidy_df
```

one more example

```{r}
litters_df = 
  read_csv(
    "./data/FAS_litters.csv",
    na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time", 
    values_to = "weight") |> 
  mutate(
    gd_time = case_match(
      gd_time,
      "gd0_weight"  ~ 0,
      "gd18_weight" ~ 18
    ))
```

##pivoting 

```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 10, 4.2, 5)
  )
```


##pivot wider for human readability 

```{r}
analysis_df |>
pivot_wider(
  names_from = "time", 
  values_from = "mean"
  ) |>
  knitr::kable()

```

##bind tables 

```{r}
fellowship_ring = 
  read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = 
  read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = 
  read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")

lotr_df = 
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "sex", 
    values_to = "words") 
```

##join FAS datasets 

Import `litters` dataset 

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA",".","")) |> janitor::clean_names() |>
  mutate(
    wt_gain = gd18_weight - gd0_weight) |>
separate(
  group, into = c("dose", "day_of_treatment"), sep = 3)
```


Import `pups` next!

```{r}
pups_df = 
  read_csv("./data/FAS_pups.csv", na = c("NA",".","")) |>
  janitor::clean_names()
  names(pups_df)

 pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
 mutate(
    sex = case_match(
      x1_male_2_female, 
      "1" ~ "male", 
      "2" ~ "female"
    )
  )
```


join the datasets!

```{r}
fas_df =
  left_join(pups_df, litters_df, by = "litter_number") |>
  relocate(litter_number, dose, day_of_treatment)
```

















